# Generated by Django 5.2.2 on 2025-08-17 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0002_product_quantity_product_unit_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='paid',
            new_name='paid_amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='pending',
            new_name='pending_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='measurement_type',
            field=models.CharField(choices=[('Quantity', 'Quantity'), ('Unit', 'Unit')], default='Quantity', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Bank', 'Bank Transfer'), ('Card', 'Card')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.CharField(choices=[('Bricks', 'செங்கல்'), ('Sand', 'மண் / மணல்'), ('Stone', 'கல்'), ('Gravel', 'சிறுகல்'), ('Cement', 'சிமெண்டு')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-17 21:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Exported', 'Exported'), ('Delivered', 'Delivered')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='san_app.order'),
        ),
    ]
