# Generated by Django 5.2.5 on 2025-08-17 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0003_rename_id_order_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit mobile number')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pincode',
            field=models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a valid 6-digit pincode')]),
        ),
    ]
