# Generated by Django 5.2.5 on 2025-08-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0004_order_qr_code_alter_customer_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
