# Generated by Django 5.2.5 on 2025-08-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0007_alter_customer_age_alter_customer_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
