# Generated by Django 5.2.5 on 2025-08-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0010_user_otp_user_otp_created_at_user_otp_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Bank', 'Bank Transfer'), ('Card', 'Card')], default='Cash', max_length=20),
        ),
    ]
