# Generated by Django 5.2.5 on 2025-08-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0011_transaction_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='product_name',
        ),
    ]
