# Generated by Django 5.2.5 on 2025-08-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0016_alter_product_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='created_at',
            new_name='paid_at',
        ),
    ]
