# Generated by Django 5.2.5 on 2025-08-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0017_rename_created_at_transaction_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.CharField(default='admin123', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='username',
            field=models.CharField(default='admin@gmail.com', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
