# Generated by Django 5.2.5 on 2025-08-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0018_device_password_device_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_status',
            field=models.CharField(default=9809890980, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='Unknown Device', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
    ]
