# Generated by Django 5.2.5 on 2025-08-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0019_device_device_status_device_name_user_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_status',
        ),
    ]
