# Generated by Django 5.2.5 on 2025-08-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0021_device_device_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='id_verify',
            field=models.BooleanField(default=True),
        ),
    ]
