# Generated by Django 5.2.5 on 2025-08-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0022_device_id_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='delivery_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
