# Generated by Django 5.2.5 on 2025-08-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0023_scanlog_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Pending', 'Pending')], default='Unpaid', max_length=20),
        ),
    ]
