# Generated by Django 5.2.5 on 2025-08-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0024_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default='25000', max_digits=10),
            preserve_default=False,
        ),
    ]
