# Generated by Django 5.2.5 on 2025-09-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0025_order_final_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pass_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pass_no',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
