# Generated by Django 5.2.5 on 2025-09-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0026_order_pass_amount_order_pass_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_per_pass',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
