# Generated by Django 5.2.5 on 2025-09-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0027_order_amount_per_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_status',
        ),
        migrations.AddField(
            model_name='device',
            name='device_state',
            field=models.CharField(default='enable', max_length=255),
            preserve_default=False,
        ),
    ]
