# Generated by Django 5.2.5 on 2025-09-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0028_remove_device_device_status_device_device_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(null=True),
        ),
    ]
