# Generated by Django 5.2.5 on 2025-09-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0029_alter_order_contact_no_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
