# Generated by Django 5.2.5 on 2025-09-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0030_alter_order_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
