# Generated by Django 5.2.5 on 2025-09-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0031_alter_scanlog_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pass_no',
            field=models.IntegerField(null=True),
        ),
    ]
