# Generated by Django 5.2.5 on 2025-09-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0032_alter_order_pass_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
