# Generated by Django 5.2.5 on 2025-09-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0033_customer_available_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Bank', 'Bank Transfer'), ('Card', 'Card'), ('Available Balance', 'Available Balance')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Bank', 'Bank Transfer'), ('Card', 'Card'), ('Available Balance', 'Available Balance')], default='Cash', max_length=20),
        ),
    ]
