# Generated by Django 5.2.5 on 2025-09-11 17:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0034_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Exported', 'Exported'), ('Delivered', 'Delivered')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Pending', 'Pending'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded')], default='Unpaid', max_length=20),
        ),
    ]
