# Generated by Django 5.2.5 on 2025-09-15 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0035_order_refunded_amount_order_refunded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('orders_cleared', models.JSONField(default=list)),
                ('excess_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_app.customer')),
            ],
        ),
    ]
