# Generated by Django 5.2.5 on 2025-09-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0036_transactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('order_payment', 'Order Payment'), ('pending_clearance', 'Pending Clearance')], default='order_payment', max_length=50),
            preserve_default=False,
        ),
    ]
