# Generated by Django 5.2.5 on 2025-09-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0038_alter_transaction_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Exported', 'Exported'), ('Delivered', 'Delivered')], default='Exported', max_length=10),
        ),
    ]
