# Generated by Django 5.2.5 on 2025-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0039_customer_is_active_product_is_active_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Booked', 'Booked')], default='Booked', max_length=10),
        ),
    ]
