# Generated by Django 5.2.5 on 2025-09-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0040_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rufund_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Bank', 'Bank Transfer'), ('Card', 'Card'), ('Available Balance', 'Available Balance')], default='Cash', max_length=20),
        ),
    ]
