# Generated by Django 5.2.5 on 2025-09-17 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0041_order_rufund_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='rufund_method',
            new_name='refund_method',
        ),
    ]
