# Generated by Django 5.2.5 on 2025-09-20 11:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0042_rename_rufund_method_order_refund_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
