# Generated by Django 5.2.5 on 2025-10-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0043_alter_customer_available_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('total_scans', models.PositiveIntegerField(default=0)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Scan Report',
                'verbose_name_plural': 'Scan Reports',
            },
        ),
    ]
