# Generated by Django 5.2.5 on 2025-10-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0044_scanreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pending_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
