# Generated by Django 5.2.5 on 2025-10-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0045_alter_transaction_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_to_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_to_current_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_to_pending_orders',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='balance_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
