# Generated by Django 5.2.5 on 2025-10-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0046_order_actual_paid_order_amount_to_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount_to_current_order',
            new_name='amount_to_order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='amount_to_pending_orders',
            new_name='amount_to_pending',
        ),
        migrations.RemoveField(
            model_name='order',
            name='balance_used',
        ),
    ]
