# Generated by Django 5.2.5 on 2025-10-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0047_rename_amount_to_current_order_order_amount_to_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='actual_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='actual_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount Paid by Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('order_payment', 'Order Payment'), ('pending_clearance', 'Pending Clearance'), ('balance_addition', 'Balance Addition'), ('balance_deduction', 'Balance Deduction')], max_length=50),
        ),
    ]
