# Generated by Django 5.2.5 on 2025-10-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0048_transaction_actual_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_breakdown_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
