# Generated by Django 5.2.5 on 2025-10-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0049_order_payment_breakdown_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='actual_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount_to_balance',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount_to_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount_to_pending',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_breakdown_data',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='actual_paid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_breakdown',
        ),
        migrations.AlterField(
            model_name='order',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default='2000', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pending_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default='900', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('order_payment', 'Order Payment'), ('pending_clearance', 'Pending Clearance')], max_length=50),
        ),
        migrations.DeleteModel(
            name='TransactionLog',
        ),
    ]
