# Generated by Django 5.2.5 on 2025-10-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0050_remove_order_actual_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='don',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_type2',
            field=models.CharField(choices=[('Quantity', 'Quantity'), ('Unit', 'Unit')], max_length=20, null=True),
        ),
    ]
