# Generated by Django 5.2.5 on 2025-10-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0051_product_don_product_measurement_type2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price2',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
            preserve_default=False,
        ),
    ]
