# Generated by Django 5.2.5 on 2025-10-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0052_product_price2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price2',
        ),
        migrations.AddField(
            model_name='product',
            name='don_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='measurement_type',
            field=models.CharField(choices=[('Quantity', 'Quantity'), ('Unit', 'Unit'), ('Don', 'Don')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bricks', 'செங்கல்'), ('Sand', 'மண் / மணல்'), ('Stone', 'கல்'), ('Gravel', 'சிறுகல்'), ('Cement', 'சிமெண்டு')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement_type',
            field=models.CharField(choices=[('Quantity', 'Quantity'), ('Unit', 'Unit'), ('Don', 'Don')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement_type2',
            field=models.CharField(choices=[('Quantity', 'Quantity'), ('Unit', 'Unit'), ('Don', 'Don')], default='unit', max_length=20),
            preserve_default=False,
        ),
    ]
