# Generated by Django 5.2.5 on 2025-10-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0053_remove_product_price_remove_product_price2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='don',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
