# Generated by Django 5.2.5 on 2025-10-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0054_order_don'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measurement_type2',
            field=models.CharField(blank=True, choices=[('Quantity', 'Quantity'), ('Unit', 'Unit'), ('Don', 'Don')], max_length=20, null=True),
        ),
    ]
