# Generated by Django 5.2.5 on 2025-10-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_app', '0055_alter_product_measurement_type2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='don',
            new_name='ton',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='don',
            new_name='ton',
        ),
        migrations.RemoveField(
            model_name='product',
            name='don_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='measurement_type2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='measurement_type',
            field=models.CharField(choices=[('Quantity', 'Quantity'), ('Unit', 'Unit'), ('Ton', 'Ton')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement_type',
            field=models.CharField(choices=[('Quantity', 'Quantity'), ('Unit', 'Unit'), ('Ton', 'Ton')], max_length=20),
        ),
    ]
